services:
    openvpn:
        image: gigster/openvpn
        restart: unless-stopped
        #working_dir: /root
        volumes:
          - ./volume:/etc/openvpn
        ports:
          - 1194:1194/udp
          - 8080:8080/tcp
        cap_add:
          - NET_ADMIN
        devices:
          - /dev/net/tun
