services:
    openvpn:
        image: gigster2000/openvpn
        restart: unless-stopped
        environment:
          - WEB_OPENVPN_PASSWORD=qwerty
        volumes:
          - ./volume:/etc/openvpn
        ports:
          - 1194:1194/udp
          - 8080:8080/tcp
        cap_add:
          - NET_ADMIN
        devices:
          - /dev/net/tun
