#!/bin/bash

if [[ "$1" == create ]]; then
		docker run -it -v ./volume:/etc/openvpn gigster/openvpn /root/server-create
        exit $?
fi

if [[ "$1" == start ]]; then
        docker compose up -d
        exit $?
fi

if [[ "$1" == stop ]]; then
        docker compose down
        exit $?
fi

echo -e "Server commands:\nserver create\nserver start\nserver stop\n\n"
